channels:
    - nodefaults
    - pytorch
    - conda-forge

name:
    dl-image-pytorch-gpu
dependencies:
    - cudatoolkit >=10.2,<11  # choose correct CUDA version for your system
    - imageio
    - aicsimageio
    - jupyter
    - nb_conda
    - pip
    - pytorch
    - scikit-image
    - scikit-learn
    - tensorboard
    - wandb
    - torchvision
    - tqdm
    - napari
    - pip:
        - cifar2png
